export const invoiceCompanyFields = [
  {
    id: "icf-1",
    title: "Company Details",
    items: [
      {
        id: "icfcd-1",
        label: "Company Name",
        name: "company-name",
        placeholder: "Awesome Company, LLC",
        type: "text",
        dbKey: "name",
        isRequired: true,
        items: null,
      },
      {
        id: "icfcd-2",
        label: "CIN",
        name: "cin",
        placeholder: "XXXXXXXXXXXXX",
        type: "text",
        dbKey: "cin",
        isRequired: true,
        items: null,
      },
      {
        id: "icfcd-3",
        label: "TIN",
        name: "tin",
        placeholder: "XXXXXXX",
        type: "text",
        dbKey: "tin",
        isRequired: true,
        items: null,
      },
    ],
  },
  {
    id: "icf-2",
    title: "Location",
    items: [
      {
        id: "icfl-1",
        label: "Address",
        name: "address",
        placeholder: "st. Street no. 111",
        type: "text",
        dbKey: "address",
        isRequired: true,
        items: null,
      },
      {
        id: "icfl-2",
        label: "Country",
        name: "country",
        placeholder: "Macedonia",
        type: "text",
        dbKey: "country",
        isRequired: true,
        items: null,
      },
      {
        id: "icfl-3",
        label: "City",
        name: "city",
        placeholder: "Kumanovo",
        type: "text",
        dbKey: "city",
        isRequired: true,
        items: null,
      },
      {
        id: "icfl-4",
        label: "Zip Code",
        name: "zip-code",
        placeholder: "1300",
        type: "text",
        dbKey: "zipCode",
        isRequired: true,
        items: null,
      },
    ],
  },
  {
    id: "icf-3",
    title: "Contact",
    items: [
      {
        id: "icfc-1",
        label: "Phone Number",
        name: "phone-number",
        placeholder: "+38977888888",
        type: "text",
        dbKey: "phoneNumber",
        isRequired: true,
        items: null,
      },
      {
        id: "icfc-2",
        label: "Email",
        name: "email",
        placeholder: "example@mail.com",
        type: "text",
        dbKey: "email",
        isRequired: true,
        items: null,
      },
      {
        id: "icfc-3",
        label: "Official Website",
        name: "website",
        placeholder: "www.awesome.com",
        type: "text",
        dbKey: "website",
        isRequired: false,
        items: null,
      },
    ],
  },
  {
    id: "icf-4",
    title: "Payment Details",
    items: [
      {
        id: "icfpd-1",
        label: "Bank Name",
        name: "bank-name",
        placeholder: "Bank Name",
        type: "text",
        dbKey: "bankName",
        isRequired: true,
        items: null,
      },
      {
        id: "icfpd-2",
        label: "Bank Account",
        name: "bank-account",
        placeholder: "ZZZ-XXXXXXXXXX-YY",
        type: "text",
        dbKey: "bankAccount",
        isRequired: true,
        items: null,
      },
    ],
  },
];
