export const serviceFields = [
  {
    id: "bdci-111",
    title: "Basic details",
    items: [
      {
        id: "sfbd-1",
        label: "Service Name*",
        name: "service-name",
        placeholder: "Marketing Strategy",
        type: "text",
        dbKey: "name",
        isRequired: true,
        items: null,
      },
      {
        id: "sfbd-2",
        label: "Description*",
        name: "service-description",
        placeholder: "Write more information about the service...",
        type: "textarea",
        dbKey: "description",
        isRequired: false,
        items: null,
      },
    ],
  },
  {
    id: "bdp-112",
    title: "Pricing",
    items: [
      {
        id: "sfp-1",
        label: "Price per unit",
        name: "service-price-unit",
        placeholder: "Write a positive number, eg: 200.",
        type: "number",
        dbKey: "pricePerHour",
        isRequired: true,
        items: null,
      },
      {
        id: "sfp-2",
        label: "Price per hour",
        name: "service-price-hour",
        placeholder: "Write a positive number, eg: 200.",
        type: "number",
        dbKey: "pricePerHour",
        isRequired: true,
        items: null,
      },
      {
        id: "sfp-3",
        label: "Tax (%)",
        name: "service-tax",
        placeholder: "Write a number between 0 and 100 (%).",
        type: "number",
        dbKey: "tax",
        isRequired: true,
        items: null,
      },
    ],
  },
  {
    id: "bdc-113",
    title: "Category",
    items: [
      {
        id: "sfc-1",
        label: "Category",
        name: "service-category",
        placeholder: "",
        type: "text",
        dbKey: "category",
        isRequired: true,
        items: [
          { id: "sfc-i-1", value: "Paid Media" },
          { id: "sfc-i-2", value: "Social Media Marketing" },
          { id: "sfc-i-3", value: "SEO" },
          { id: "sfc-i-4", value: "Content Writing" },
          { id: "sfc-i-5", value: "E-Commerce" },
          { id: "sfc-i-6", value: "Branding" },
          { id: "sfc-i-7", value: "Graphic Design" },
          { id: "sfc-i-8", value: "Web Design" },
          { id: "sfc-i-9", value: "Data Analysis" },
          { id: "sfc-i-10", value: "Video Editing & Production" },
          { id: "sfc-i-11", value: "Consulting" },
          { id: "sfc-i-12", value: "Web Development" },
          { id: "sfc-i-13", value: "Digital Marketing" },
        ],
      },
      {
        id: "sfc-2",
        label: "SKU*",
        name: "service-sku",
        placeholder: "XYZ-2738",
        type: "text",
        dbKey: "sku",
        isRequired: true,
        items: null,
      },
    ],
  },
  {
    id: "bdi-114",
    title: "Images",
    subtitle: "Images will appear in the services list",
    items: [
      {
        id: "sfi-1",
        label: "Image",
        name: "service-image",
        placeholder: "Add Image",
        type: "file",
        dbKey: "serviceImage",
        isRequired: false,
        items: null,
      },
    ],
  },
];
