export const newCustomerFields = [
  {
    id: "ncf-1",
    label: "Company Name",
    placeholder: "Awesome, LLC",
    name: "company-name",
    type: "text",
    dbKey: "companyName",
    isRequired: true,
  },
  {
    id: "ncf-2",
    label: "Bank Account",
    placeholder: "XXX-XXXXXXXXXX-XX",
    name: "bank-account",
    type: "text",
    dbKey: "bankAccount",
    isRequired: false,
  },
  {
    id: "ncf-3",
    label: "Email",
    placeholder: "awesome@example.com",
    name: "email",
    type: "text",
    dbKey: "email",
    isRequired: true,
  },
  {
    id: "ncf-4",
    label: "Phone number",
    placeholder: "+38977886622",
    name: "phone-number",
    type: "text",
    dbKey: "phoneNumber",
    isRequired: true,
  },
  {
    id: "ncf-5",
    label: "EDB (ID#1)",
    placeholder: "XXXXXXXXXXXXX",
    name: "edb",
    type: "text",
    dbKey: "edb",
    isRequired: true,
  },
  {
    id: "ncf-6",
    label: "EMBS (ID#2)",
    placeholder: "XXXXXX",
    name: "embs",
    type: "text",
    dbKey: "embs",
    isRequired: true,
  },
  {
    id: "ncf-7",
    label: "Country",
    placeholder: "Macedonia",
    name: "country",
    type: "text",
    dbKey: "country",
    isRequired: true,
  },
  {
    id: "ncf-8",
    label: "State/Region",
    placeholder: "Kumanovo",
    name: "state-region",
    type: "text",
    dbKey: "stateRegion",
    isRequired: true,
  },
  {
    id: "ncf-9",
    label: "Zip Code",
    placeholder: "1300",
    name: "zip-code",
    type: "text",
    dbKey: "zipCode",
    isRequired: true,
  },
  {
    id: "ncf-10",
    label: "Address",
    placeholder: "St. James Bond no. 007",
    name: "address",
    type: "text",
    dbKey: "address",
    isRequired: true,
  },
];

export const addCustomerDbKeys = [
  {
    id: "acdbk-1",
    name: "company-name",
    dbKey: "companyName",
  },
  {
    id: "acdbk-2",
    name: "bank-account",
    dbKey: "bankAccount",
  },
  {
    id: "acdbk-3",
    name: "email-address",
    dbKey: "emailAddress",
  },
  {
    id: "acdbk-4",
    name: "phone-number",
    dbKey: "phoneNumber",
  },
  {
    id: "acdbk-5",
    name: "edb",
    dbKey: "edb",
  },
  {
    id: "acdbk-6",
    name: "embs",
    dbKey: "embs",
  },
  {
    id: "acdbk-7",
    name: "country",
    dbKey: "country",
  },
  {
    id: "acdbk-8",
    name: "state-region",
    dbKey: "stateRegion",
  },
  {
    id: "acdbk-9",
    name: "zip-code",
    dbKey: "zipCode",
  },
  {
    id: "acdbk-10",
    name: "address",
    dbKey: "address",
  },
];
